$mod = SUPER

# App launchers
bind = $mod, Return, exec, kitty
bind = $mod, D, exec, fuzzel

# Window management
bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod, Space, togglefloating

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

# Brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Screenshots
bind = , XF86SelectiveScreenshot, exec, grimblast copy area
bind = CTRL, XF86SelectiveScreenshot, exec, grimblast save area ~/Pictures/Screenshots/
