# Float dialogs
windowrule = float, title:^(Open File)$
windowrule = float, title:^(Save File)$

# Float specific apps
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(nm-connection-editor)$

# Center floating windows
windowrule = center, floating:1
